//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosetTable
    {
        public int ClosetID { get; set; }
        public int TopsID { get; set; }
        public int BottomsID { get; set; }
        public int ShoesID { get; set; }
        public int HatsID { get; set; }
    
        public virtual BottomsTable BottomsTable { get; set; }
        public virtual HatsTable HatsTable { get; set; }
        public virtual ShoesTable ShoesTable { get; set; }
        public virtual TopsTable TopsTable { get; set; }
    }
}
