//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeEntities : DbContext
    {
        public WardrobeEntities()
            : base("name=WardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BottomsTable> BottomsTables { get; set; }
        public virtual DbSet<ClosetTable> ClosetTables { get; set; }
        public virtual DbSet<HatsTable> HatsTables { get; set; }
        public virtual DbSet<ShoesTable> ShoesTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TopsTable> TopsTables { get; set; }
    }
}
